### ISSUE TITLE
BNB smart chain error when adding modules

### ISSUE THREAD

**Issue by samepant** [gnosis/zodiac-safe-app#60]
Seeing this error when attempting to add a module on BNB:
```
2RealityModuleModal.tsx:140 Error deploying module:  TypeError: Cannot read properties of undefined (reading 'realityETH')
    at Object.t.getFactoryAndMasterCopy (factory.js:59:31)
    at t.deployAndSetUpModule (factory.js:7:41)
    at J (index.ts:142:7)
    at RealityModuleModal.tsx:129:19
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at n (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
```
Transaction window never pops up.

**Comment by samepant** [comment]
this issue appears to be the same error https://github.com/gnosis/zodiac/issues/56

**Comment by NeoXtreem** [comment]
@samepant How's it going with this fix?

**Comment by carlosfebres** [comment]
That issue got solved in this PR https://github.com/gnosis/zodiac/pull/55. We need to update the Zodiac app to use Zodiac v1.0.11.

**Comment by samepant** [comment]
fixed in this release: https://github.com/gnosis/zodiac-safe-app/releases/tag/v1.0.7
